### ISSUE TITLE
install_piweb.sh giving an error

### ISSUE THREAD

**Issue by stuart-thackray** [umbrellary/piweb#2]
Hi I was able to install maven; and do the build which succeded in the build/install directroy I am getting the following error; which I am not sure what it is being caused by 

pi@raspberrypi ~/piweb/build/install $ ./install_piweb.sh 
Hit http://mirrordirector.raspbian.org wheezy Release.gpg
Hit http://raspberrypi.collabora.com wheezy Release.gpg
Hit http://mirrordirector.raspbian.org wheezy Release
Hit http://archive.raspberrypi.org wheezy Release.gpg
Hit http://mirrordirector.raspbian.org wheezy/main armhf Packages     
Hit http://raspberrypi.collabora.com wheezy Release
Hit http://archive.raspberrypi.org wheezy Release                                        
Hit http://mirrordirector.raspbian.org wheezy/contrib armhf Packages                     
Hit http://raspberrypi.collabora.com wheezy/rpi armhf Packages                          
Hit http://archive.raspberrypi.org wheezy/main armhf Packages                           
Hit http://mirrordirector.raspbian.org wheezy/non-free armhf Packages
Hit http://mirrordirector.raspbian.org wheezy/rpi armhf Packages                        
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en_US                       
Ign http://archive.raspberrypi.org wheezy/main Translation-en_US                        
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en    
Ign http://archive.raspberrypi.org wheezy/main Translation-en     
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en_US
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en_US
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en_US
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en_US
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package wifite
E: Unable to locate package jq
mkdir: cannot create directory `/etc/hostapd': File exists
sudo: systemctl: command not found
sudo: systemctl: command not found
sudo: systemctl: command not found

**Comment by stuart-thackray** [comment]
I think I can ignore those errors; however what I can determine is that maybe I have the wrong java version am getting 

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/umbrellary/Application : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at java.lang.Thread.run(Thread.java:701)

The java version returned is the following. 

pi@raspberrypi ~/piweb/build/app $ java -version
java version "1.6.0_38"
OpenJDK Runtime Environment (IcedTea6 1.13.10) (6b38-1.13.10-1~deb7u1+rpi1)
OpenJDK Zero VM (build 23.25-b01, mixed mode)

**Comment by umbrellary** [comment]
sorry, wifite and jq is not need for piweb...
this project need to use java8, and only support for raspberry pi3.

**Comment by stuart-thackray** [comment]
Alright thanks; will have to give it a go when I get the pi3

**Comment by stuart-thackray** [comment]
Hi i have gotten a pi3 & fresh install of (RASPBIAN JESSIE)[https://www.raspberrypi.org/downloads/raspbian/]

I am still getting a java issue. Is there a means by which to get java 8 / a different OS I need to use?

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/umbrellary/Application : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by umbrellary** [comment]
You must install Oracle java 8 on JESSIE

**Comment by stuart-thackray** [comment]
alright eventually downloaded the right java;and it is working now. Very good looking interface :) 

I am struggling with inputs though. I have an input wired on GPIO_06 when I press the input I don't see anything; should I see something? 

I will close issue as got it working but would be very interested in other tabs and their uses also about the configuration; if there is maybe a means to get all the other GPIO pins mapped (not just the only GPIO pin)
